packages:
  - "packages/*"
  - "demos/*"

allowBuilds:
  esbuild: false
  workerd: false

# Define a catalog of version ranges.
catalog:
  ziko: latest
  '@zikojs/mdx': latest
  vite: latest
  "@rollup/pluginutils": latest
  "@zikojs/mdx-highlightjs-adapter": latest
  "@zikojs/mdx-prismjs-adapter": latest

minimumReleaseAgeExclude:
  - '@zikojs/mdx@0.4.2'
