packages:
  - "packages/*"
  - "demos/*"

allowBuilds:
  esbuild: false
  workerd: false

# Define a catalog of version ranges.
catalog:
  ziko: latest
  '@zikojs/mdx': latest
  vite: latest
  "@rollup/pluginutils": latest
  "@zikojs/mdx-highlightjs-adapter": latest
  "@zikojs/mdx-prismjs-adapter": latest

# minimumReleaseAgeExclude:
#   - '@zikojs/mdx@0.4.2'

minimumReleaseAgeExclude:
  - ziko@2.0.0-beta.14
  - '@zikojs/mdx@0.5.1'
